# Site settings
title: Hard at play
description: A personal portfolio website
baseurl: "/portfolioweb" # the subpath of your site, e.g. /blog
url: "verma16Ayush.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ayush Verma
user_description: Junior at Electronics and Comms. Engineering undergrad at NITH. An aspiring software and video game developer. Data Science and Machine Learning Enthusiast.
user_title: Aspiring Software Developer
email: verma16.ayush@gmail.com
twitter_username: vermaAyush16
github_username:  verma16Ayush

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
